name: Release

on:
  release:
    types: [prereleased, released]

jobs:
  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment:
      name: pypi-release
      url: https://pypi.org/p/tomescripts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install build dependencies
        run: python -m pip install --upgrade pip build

      - name: Build the package
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  deploy-docs:
    name: Deploy Documentation
    needs: publish
    uses: ./.github/workflows/deploy-docs.yml
    with:
      version: ${{ github.event.release.tag_name }}
    permissions:
      contents: write
